Algoritmo "idades"
Var
idade1, idade2: inteiro
mediaIdade: real
nome1, nome2: caractere
Inicio
escreva("Digite um nome ")
leia(nome1)
escreva("Digite a idade de ", nome1, " ")
leia(idade1)
escreva("Digite outro nome ")
leia(nome2)
escreva("Digite a idade de ", nome2, " ")
leia(idade2)
mediaIdade <- (idade1 + idade2) / 2
escreval("Adidade média de ", nome1, " e ", nome2, " é de ", mediaIdade, " anos")
Fimalgoritmo
