Algoritmo "terreno"
Var
largura, comprimento, metroQuadrado, valorArea, valorPreco : real
Inicio
escreva("Digite a largura do terreno ")
leia(largura)
escreva("Digite o comprimento do terreno ")
leia(comprimento)
escreva("Digite o valor do metro quadrado ")
leia(valorPreco)
metroQuadrado <- largura * comprimento
valorArea <- metroQuadrado * valorPreco
escreval("Area do terreno: ", metroQuadrado:2:2)
escreval("Preço do terreno: ", valorArea:2:2)
Fimalgoritmo
