Algoritmo "consumo"
Var
A, B, C, quadrado, triangulo, trapezio: real
Inicio
escreva("Digite a medida de A ")
leia(A)
escreva("Digite a medida de B ")
leia(B)
escreva("Digite a medida de C ")
leia(C)
quadrado <- A * A
triangulo <- (A * B) / 2
trapezio <- (C * (A + B)) / 2
escreval("Área do quadrado: ", quadrado:4:4)
escreval("Área do triangulo: ", triangulo:4:4)
escreval("Área do trapezio: ", trapezio:4:4)
Fimalgoritmo
